### ISSUE TITLE
Theme?

### ISSUE THREAD

**Issue by Ileriayo** [lorisleiva/blog#8]
Hi, @lorisleiva, you've got a beautiful design for your blog there.
How about turning it into a standalone theme since it's MIT(license).
I'd be glad to contribute.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid I like changing my blog too often to make it a global theme as I'll have to maintain the theme as-is which will prevent me from experiencing new blog design and ideas.

That being said, feel free to create and support a theme inspired by this current version of my blog. 🙂
